# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _layout
else:
    import _layout

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def dimension_check(kd):
    return _layout.dimension_check(kd)

def unweighted_edge_check(len_I, len_J):
    return _layout.unweighted_edge_check(len_I, len_J)

def weighted_edge_check(len_I, len_J, len_V):
    return _layout.weighted_edge_check(len_I, len_J, len_V)

def layout_unweighted(X, I, J, t_max, eps, rseed):
    return _layout.layout_unweighted(X, I, J, t_max, eps, rseed)

def layout_weighted(X, I, J, V, t_max, eps, rseed):
    return _layout.layout_weighted(X, I, J, V, t_max, eps, rseed)

def layout_unweighted_convergent(X, I, J, t_max, eps, delta, t_maxmax, rseed):
    return _layout.layout_unweighted_convergent(X, I, J, t_max, eps, delta, t_maxmax, rseed)

def layout_weighted_convergent(X, I, J, V, t_max, eps, delta, t_maxmax, rseed):
    return _layout.layout_weighted_convergent(X, I, J, V, t_max, eps, delta, t_maxmax, rseed)

def layout_sparse_unweighted(X, I, J, p, t_max, eps, rseed):
    return _layout.layout_sparse_unweighted(X, I, J, p, t_max, eps, rseed)

def layout_sparse_weighted(X, I, J, V, p, t_max, eps, rseed):
    return _layout.layout_sparse_weighted(X, I, J, V, p, t_max, eps, rseed)

def mds_direct(X, d, w, eta, rseed, lambda_repulsion, repulsion_power):
    return _layout.mds_direct(X, d, w, eta, rseed, lambda_repulsion, repulsion_power)

